NAME	= libft.a

CC	= cc
CFLAGS	= -Wall -Wextra -Werror

AR	= ar rcs
RM	= rm -f

SRCS	= ft_memchr.c     ft_strncmp.c	ft_bzero.c	ft_lstadd_front.c  ft_memcmp.c\
	  ft_strchr.c    ft_strrchr.c	ft_memcpy.c	ft_strdup.c	ft_strnstr.c\
	  ft_isalnum.c    ft_memmove.c	ft_isalpha.c	ft_memset.c	ft_isascii.c\
	  ft_strlcat.c	ft_tolower.c	ft_isdigit.c	ft_strlcpy.c	ft_toupper.c\
	  ft_isprint.c	ft_strlen.c\	

OBJS	= $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(AR) $(NAME) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	$(RM) $(OBJS)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re

